services:
  resume-screening:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: future_ml_task3_resume_screening
    volumes:
      - ./data:/app/data
    command:
      [
        "python",
        "-m",
        "src.run_pipeline",
        "--resumes",
        "data/raw/resumes_sample.csv",
        "--job",
        "data/raw/job_description_data_scientist.txt",
        "--role",
        "data_scientist",
        "--output",
        "data/processed"
      ]

  recruiter-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: future_ml_task3_recruiter_ui
    volumes:
      - ./data:/app/data
    ports:
      - "8501:8501"
    command:
      [
        "streamlit",
        "run",
        "streamlit_app.py",
        "--server.address=0.0.0.0",
        "--server.port=8501"
      ]
